Cloud Config's compilation VMs are no longer pre-emptible
fixes:
```
Error: Timed out sending 'compile_package' to 37389d83-bcfc-4752-a2ff-6954bf79b5f6 after 45 seconds
```

[#133624767](https://www.pivotaltracker.com/story/show/133624767)

Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>